src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'registrations', sessions: 'users/sessions' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root 'pages#top'
  get  'pages/about' => 'pages#about'
  get  'pages/terms' => 'pages#terms'
  get  'pages/policy' => 'pages#policy'
  resources :users
  resources :posts do
    resources :photos, only: %i[create]
    resources :maps, only: %i[create]
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
end

src/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

src/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

src/app/models/map.rb
class Map < ApplicationRecord
  belongs_to :post

  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

src/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

src/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :map, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos
  accepts_nested_attributes_for :map

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

src/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  validates :profile_photo, presence: true
  mount_uploader :profile_photo, ImageUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.profile_photo = Rack::Test::UploadedFile.new(Rails.root.join('app/assets/images/guest.png'), 'image/png')
    end
  end

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

src/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name profile_photo])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name profile_photo])
  end
end

src/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private

  def comment_params
    params.required(:comment).permit(:user_id, :post_id, :comment)
  end
end

src/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    respond_to :js if @like.save
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    respond_to :js if @like.destroy
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

src/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end

  def terms; end

  def top
    @post = Post.new
    @post.photos.build
    @post.build_map
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).limit(10).includes(:map, :photos, :user).order('created_at DESC')
  end
end

src/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def create
    @post = Post.new(post_params)
    redirect_to posts_path
    if @post.save
      flash[:notice] = "投稿が保存されました"
    else
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @post = Post.new
    @post.photos.build
    @post.build_map
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).limit(10).includes(:map, :photos, :user).order('created_at DESC')
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to posts_path
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿が保存されました"
      redirect_to posts_path
    else
      flash[:alert] = "投稿に失敗しました"
      redirect_to edit_post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:caption, map_attributes: %i[address latitude longitude], photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

src/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def update
    super
    update_internal
  end

  def destroy
    super
    destroy_internal
  end

  def update_internal; end

  def destroy_internal; end

  def ensure_normal_user
    redirect_to posts_path, alert: 'ゲストユーザーの変更・削除はできません。' if resource.email == 'guest@example.com'
  end

  protected

  def after_sign_up_path_for(_resource)
    posts_path
  end

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

src/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def after_sign_in_path_for(_resource)
    posts_path
  end
end

src/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    gon.users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @post = Post.new
    @post.photos.build
    @post.build_map
    @posts = @user.posts.limit(10).includes(:map, :photos, :user).order('created_at DESC')
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to posts_path
  end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BASE_TITLE = "ストバスぽっと"
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} - #{BASE_TITLE}"
    end
  end
end

src/app/helpers/comments_helper.rb
module CommentsHelper
end

src/app/helpers/likes_helper.rb
module LikesHelper
end

src/app/helpers/pages_helper.rb
module PagesHelper
end

src/app/helpers/posts_helper.rb
module PostsHelper
end

src/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

src/app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_comment').val("");

src/app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", { post: @post } %>');

src/app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいねを取り消す", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= @post.likes.count %>');

src/app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= @post.likes.count %>');

src/app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

src/app/views/posts/_new.html.erb
<aside class="col-xl-4 col-lg-4 col-md-5 col-sm-12 mt-3 ml-5 mx-auto">
  <div class="d-flex flex-column align-items-center mt-3 w-100">
    <div class="w-100 post-card">
      <div class="card">
        <div class="post-body">
          <div class="form-group">
            <label>レビュー場所（Google Mapで検索)</label>
            <div class="search-form">
              <input id="address" class="form-control" type="textbox" placeholder="公園名や地名、住所を入力してください">
              <button type="button" class="search-button" value="検索" onclick="codeAddress()">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
          <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
            <div class="form-group">
              <%= f.label :address, "住所" %>
              <span class="label-required">必須</span>
                <%= f.fields_for :map, @post.build_map do |m| %>
                  <%= m.text_field :address, class: "form-control", placeholder: "住所を入力してください", name: "post[map_attributes][address]", id: "hidden_address",  required: true %>
                  <%= m.hidden_field :latitude %>
                  <%= m.hidden_field :longitude %>
                <% end %>
            </div>
            <div class="form-group mb-3">
              <div class="col-auto pr-0"></div>
              <%= f.label :caption, "テキスト" %>
              <div>
                <%= f.text_field :caption, class: "form-control", placeholder: "コメントを入力してください" %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.fields_for :photos do |i| %>
                <%= i.file_field :image %>
              <% end %>
            </div>
              <%= f.submit "投稿する", class: "btn btn-primary" %>
            <% end %>
              <%= render 'partial/modal' %>
        </div>
      </div>
    </div>
  </div>
</aside>

src/app/views/posts/_post_list.html.erb
<% @posts.each do |post| %>
  <div class="col-xl-11 col-lg-11 col-md-12">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag post.user.profile_photo_url, class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration", title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>
          <% if post.user_id == current_user.id %>
            <%= link_to edit_post_path(post), method: :get, class: "edit-post-icon-outline ml-auto mx-0 my-auto", id:"edit-post-icon" do %>
              <div class="edit-post-icon"></div>
            <% end %>            
            <%= link_to post_path(post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "delete-post-icon-outline ml-auto mx-0 my-auto", id: "delete-post-icon" do %>
              <div class="delete-post-icon"></div>
            <% end %>
          <% end %>
        </div>
        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url, class: "post-image" if post.photos.present? %>
        <% end %>
        <div class="card-body">
          <%= link_to(post_path(post)) do %>
            <span><%= post.map&.address %></span>
          <% end %>
          <div class="mr-2"><span><%= post.caption %></span></div>
          <div id="comment-post-<%= post.id.to_s %>"><%= render 'comment_list', { post: post } %></div>
          <div class="parts">
            <div id="like-icon-post-<%= post.id.to_s %>">   
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text", id: "loved-hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text", id: "love-hide-text" %>
              <% end %>
            </div>
            <div id="like-text-post-<%= post.id.to_s %>"><%= post.likes.count %></div>
              <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
          </div>
          <hr>
          <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
            <%= form_with model: [post, Comment.new], class: "w-100", local: false do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: post.id %>
              <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

src/app/views/posts/edit.html.erb
<% provide(:title, "投稿編集") %>
<div class="show-address"><span><%= @post.map&.address %></span></div>
<style>
#map {
  height: 50vh;
  width: 60vw;
  margin: 0 auto;
}
</style>
<div id="map"></div>
<script>
let map
let geocoder
function initMap() {
    var test = {lat: <%= @post.map&.latitude %>, lng: <%= @post.map&.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '<%= @post.map&.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });

    var geocoder = new google.maps.Geocoder();
    
    map.addListener('click', function(e){
      geocoder.geocode({location: e.latLng}, function(results, status){
        if(status === 'OK' && results[0]) {

          var marker = new google.maps.Marker({
            position: e.latLng,
            map: map,
            title: results[0].formatted_address,
            animation: google.maps.Animation.DROP
          });

          var infoWindow = new google.maps.InfoWindow({
            content:  results[0].formatted_address,
            pixelOffset: new google.maps.Size(0, 5)
          });
  
          marker.addListener('click', function(){
            infoWindow.open(map, marker);
          });
          
          infoWindow.addListener('closeclick', function(){
            marker.setMap(null);
          });
        }else if(status === 'ZERO_RESULTS') {
          alert('不明なアドレスです： ' + status);
          return;
        }else{
          alert('失敗しました： ' + status);
          return;
        }
      });
    });
  }

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      let marker = new google.maps.Marker({
      map: map,
      position: results[0].geometry.location
      });

        let infoWindow = new google.maps.InfoWindow({
            content:  inputAddress,
            pixelOffset: new google.maps.Size(0, 5)
          });
  
          marker.addListener('click', function(){
            infoWindow.open(map, marker);
          });
          
          infoWindow.addListener('closeclick', function(){
            marker.setMap(null);
          });

        let address = document.getElementById('address');
        address.setAttribute("value", inputAddress);

        let hidden_address = document.getElementById('hidden_address');
        hidden_address.setAttribute("value", inputAddress);
    } else {
        alert('該当する結果がありませんでした：' + status);
      }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

<div class="row">
  <div class="col-xl-6 col-lg-8 col-md-10 col-sm-12 align-items-center mx-auto ">
    <div class="post-card">
      <div class="card">
        <div class="post-body">
          <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
            <div class="form-group">
              <%= f.label :address, "住所" %>
              <span class="label-required">必須</span>
              <div>
                <%= f.fields_for :map, @post.build_map do |m| %>
                  <%= m.text_field :address, class: "form-control", placeholder: "住所", name: "post[map_attributes][address]", id: "hidden_address", autofocus: true, required: true %>
                <% end %>
              </div>
            <div class="form-group mb-3">
              <div class="col-auto pr-0"></div>
              <%= f.label :caption, "テキスト" %>
              <div>
                <%= f.text_field :caption, class: "form-control", placeholder: "コメントを入力する" %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.fields_for :photos do |i| %>
                <%= i.file_field :image %>
              <% end %>
            </div>
              <%= f.submit "編集する", class: "btn btn-primary" %>
          <% end %>
              <%= render 'partial/modal' %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/app/views/posts/index.html.erb
<% provide(:title, "投稿一覧") %>
<%= render 'partial/map' %>
<div class="row">
  <%= render 'posts/new' %>
  <div class="feed col-md-7 mt-3 mx-auto">
    <div class="recent-posts">
      <%= search_form_for @q do |f| %>
        <%= f.label :user_name_or_map_address_or_caption, "最近の投稿", class: "recent-posts" %>
        <div class="col-xl-11 col-lg-11 col-md-12 recent-postsform">
          <%= f.search_field :user_name_or_map_address_or_caption_cont, class: "form-control", placeholder: "投稿を検索" %>
          <%= f.button type: "submit", value: "投稿を検索", class: "search-button", id: 'search-button' do %>
            <i class='fas fa-search' ></i>
          <% end %>
        </div>
        <% if @posts.count == 0 %>
          <p>投稿が見つかりません</p>
        <% end %>
      <% end %>
    </div>
  <%= render 'posts/post_list' %>
  </div>
</div>

src/app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "コメントを書く" %>
            </div>
          </div>
          <div class="mb-3">

            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image %>
            <% end %>

          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

src/app/views/posts/show.html.erb
<% provide(:title, "投稿詳細") %>
<div class="show-address"><span><%= @post.map&.address %></span></div>
<style>
#map {
  height: 50vh;
  width: 60vw;
  margin: 0 auto;
}
</style>
<div id="map"></div>
<script>
function initMap() {
    var test = {lat: <%= @post.map&.latitude %>, lng: <%= @post.map&.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '<%= @post.map&.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

<div class="col-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-9 col-sm-9 col-xs-7 mx-auto">
      <div class="card-left mx-auto">
        <%= image_tag @post.photos.first.image.url,class: "card-img-top", alt: "no image" if @post.photos.present? %>
      </div>
    </div>
    <div class="card-show col-md-9 col-sm-9 col-xs-7 mx-auto mt-3">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
            <%= image_tag @post.user.profile_photo_url, class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>
            <% if @post.user_id == current_user.id %>
              <%= link_to edit_post_path(@post), method: :get, class: "delete-post-icon-outline ml-auto mx-0 my-auto" do %>
                <div class="edit-post-icon"></div>
              <% end %>
              <%= link_to post_path(@post), method: :delete, class: "delete-post-icon-outline ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon"></div>
              <% end %>
            <% end %>
          </div>
          <div class="m-2">
            <strong><%= @post.caption %></strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>
            </div>
          </div>
        </div>
        <div class="parts">
          <div id="like-icon-post-<%= @post.id.to_s %>">   
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>                  
          <div id="like-text-post-<%= @post.id.to_s %>">
            <%= @post.likes.count %>
          </div>
          <div class="show-post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        </div>
      </div>
    </div>
  </div>
</div>

src/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-4 profile-wrap">  
    <div class="text-center">
      <%= image_tag @user.profile_photo_url, class: "round-img" %>
        <h1><%= @user.name %></h1> 
        <% if @user == current_user %>    
          <p><%= @user.email %></p>
          <button type="button" class="setting col-md-4" data-toggle="modal" data-target="#exampleModal"></button>
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="list-group text-center">
                  <%= link_to "プロフィールを編集", edit_user_registration_path, class: "list-group-item list-group-item-action" %>
                  <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                  <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
  <div class="col-md-8">
    <h5>投稿一覧</h5>
    <% @posts.each do |post| %>
      <div class="col-md-10">
        <div class="card-wrap">
          <div class="card">
            <div class="card-header align-items-center d-flex">
              <%= link_to user_path(post.user), class: "no-text-decoration" do %>
              <%= image_tag post.user.profile_photo_url, class: "post-profile-icon" %>
              <% end %>
              <%= link_to user_path(post.user), class: "black-color no-text-decoration",
                title: post.user.name do %>
                <strong><%= post.user.name %></strong>
              <% end %>
              <% if post.user_id == current_user.id %>
                <%= link_to edit_post_path(post), method: :get, class: "delete-post-icon-outline ml-auto mx-0 my-auto" do %>
                  <div class="edit-post-icon"></div>
                <% end %>    
                <%= button_to post_path(post), method: :delete, class: "delete-post-icon-outline ml-auto mx-0 my-auto" do %>
                  <div class="delete-post-icon"></div>
                <% end %>
              <% end %>
            </div>
            <%= link_to(post_path(post)) do %>
                <%= image_tag post.photos.first.image.url, class: "post-image" if post.photos.present? %>
            <% end %>
            <div class="card-body">
              <%= link_to(post_path(post)) do %>
                <span><%= post.map&.address %></span>
              <% end %>
                <span><%= post.caption %></span>
                <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
                <div id="comment-post-<%= post.id.to_s %>">
                  <%= render 'posts/comment_list', { post: post } %>
                </div>
                <div class="parts">
                  <div id="like-icon-post-<%= post.id.to_s %>">   
                    <% if post.liked_by(current_user).present? %>
                      <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                    <% else %>
                      <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                    <% end %>
                  </div>                  
                  <div id="like-text-post-<%= post.id.to_s %>">
                    <%= post.likes.count %>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>