src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'registrations', sessions: 'users/sessions' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root 'pages#top'
  get  'pages/about' => 'pages#about'
  get  'pages/terms' => 'pages#terms'
  get  'pages/policy' => 'pages#policy'
  resources :users
  resources :posts do
    resources :photos, only: %i[create]
    resources :maps, only: %i[create]
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
end

src/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

src/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

src/app/models/map.rb
class Map < ApplicationRecord
  belongs_to :post

  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

src/app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

src/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :map, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos
  accepts_nested_attributes_for :map

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

src/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  validates :profile_photo, presence: true
  mount_uploader :profile_photo, ImageUploader

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.profile_photo = Rack::Test::UploadedFile.new(Rails.root.join('app/assets/images/guest.png'), 'image/png')
    end
  end

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

src/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name profile_photo])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name profile_photo])
  end
end

src/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private

  def comment_params
    params.required(:comment).permit(:user_id, :post_id, :comment)
  end
end

src/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    respond_to :js if @like.save
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    respond_to :js if @like.destroy
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

src/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end

  def terms; end

  def top
    @post = Post.new
    @post.photos.build
    @post.build_map
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).limit(10).includes(:map, :photos, :user).order('created_at DESC')
  end
end

src/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def create
    @post = Post.new(post_params)
    redirect_to posts_path
    if @post.save
      flash[:notice] = "投稿が保存されました"
    else
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @post = Post.new
    @post.photos.build
    @post.build_map
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).limit(10).includes(:map, :photos, :user).order('created_at DESC')
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to posts_path
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿が保存されました"
      redirect_to posts_path
    else
      flash[:alert] = "投稿に失敗しました"
      redirect_to edit_post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:caption, map_attributes: %i[address latitude longitude], photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

src/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def update
    super
    update_internal
  end

  def destroy
    super
    destroy_internal
  end

  def update_internal; end

  def destroy_internal; end

  def ensure_normal_user
    redirect_to posts_path, alert: 'ゲストユーザーの変更・削除はできません。' if resource.email == 'guest@example.com'
  end

  protected

  def after_sign_up_path_for(_resource)
    posts_path
  end

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end
end

src/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    gon.users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @post = Post.new
    @post.photos.build
    @post.build_map
    @posts = @user.posts.limit(10).includes(:map, :photos, :user).order('created_at DESC')
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to posts_path
  end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BASE_TITLE = "ストバスぽっと"
  def full_title(page_title)
    if page_title.blank?
      BASE_TITLE
    else
      "#{page_title} - #{BASE_TITLE}"
    end
  end
end

src/app/helpers/comments_helper.rb
module CommentsHelper
end

src/app/helpers/likes_helper.rb
module LikesHelper
end

src/app/helpers/pages_helper.rb
module PagesHelper
end

src/app/helpers/posts_helper.rb
module PostsHelper
end

src/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script> 
  </head>
  <body>
    <%= render 'partial/navbar' %>
        <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
      <div class="container">
    <%= yield %>
      </div>
    <%= render 'partial/footer' %>
  </body>
</html>

src/app/views/pages/about.html.erb
<% provide(:title, "ストバスぽっと とは？") %>
<div class="about">
  <h1>「ストバスぽっと」とは?</h1>
  <p>「ストバスぽっと」はバスケットボールのゴールが設置してある公園を共有するサービスです。</p>
  <div class="basketball"></div>
  <p>
  外でバスケットボールをしたい時、ゴールスポットを知りたい時、是非「ストバスぽっと」を是非ご利用ください。
  <br>
  ゴールがある公園の状況を全国のユーザーと共有することができます。
  <br>
  「ストバスぽっと」を利用することで全国のユーザーと情報を交換し、運動不足を解消することができます。
  <br>
  さあ、今すぐ「ストバスぽっと」に登録し、素敵な時間を過ごしましょう！
  </p>
  <%= link_to "今すぐ登録する！", new_user_registration_path, class: " about-button btn-primary" %>
</div>

src/app/views/pages/terms.html.erb
<% provide(:title, "利用規約") %>
<div class="terms" >
  <h1>利用規約</h1>
  <h3>この利用規約（以下，「本規約」といいます。）は，ストバスぽっと（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。 登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</h3>
  <h2>第1条（適用）</h2>
    <p>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。 当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。 本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</p>
  <h2>第2条（利用登録）</h2>
    <p>本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこの承認を登録希望者に通知することによって，利用登録が完了するものとします。 当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。 利用登録の申請に際して虚偽の事項を届け出た場合 本規約に違反したことがある者からの申請である場合 その他，当社が利用登録を相当でないと判断した場合</p>
  <h2>第3条（パスワードの管理）</h2>
    <p>ユーザーは，自己の責任において，本サービスのパスワードを適切に管理するものとします。 ユーザーは，いかなる場合にも，パスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，パスワードが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。 パスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</p>
  <h2>第4条（利用料金および支払方法）</h2>
    <p>本サービスは如何なる利用料金もユーザーに請求いたしません。ご安心してご利用ください。</p>
  <h2>第5条（禁止事項）</h2>
    <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。 法令または公序良俗に違反する行為 犯罪行為に関連する行為 当社，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為 当社のサービスの運営を妨害するおそれのある行為 他のユーザーに関する個人情報等を収集または蓄積する行為 不正アクセスをし，またはこれを試みる行為 他のユーザーに成りすます行為 当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為 当社，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為 以下の表現を含み，または含むと当社が判断する内容を本サービス上に投稿し，または送信する行為 過度に暴力的な表現 露骨な性的表現 人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現 自殺，自傷行為，薬物乱用を誘引または助長する表現 その他反社会的な内容を含み他人に不快感を与える表現 以下を目的とし，または目的とすると当社が判断する行為 営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。） 性行為やわいせつな行為を目的とする行為 面識のない異性との出会いや交際を目的とする行為 他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為 当社，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為 その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為 宗教活動または宗教団体への勧誘行為 その他，当社が不適切と判断する行為
  当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</p>
  <h2>第6条（本サービスの提供の停止等）</h2>
    <p>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合 コンピュータまたは通信回線等が事故により停止した場合 その他，当社が本サービスの提供が困難と判断した場合 当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</p>
  <h2>第7条（著作権）</h2>
    <p>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。 ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当社は，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。 前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</p>
  <h2>第8条（利用制限および登録抹消）</h2>
    <p>当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。 本規約のいずれかの条項に違反した場合 登録事項に虚偽の事実があることが判明した場合 決済手段として当該ユーザーが届け出たクレジットカードが利用停止となった場合 料金等の支払債務の不履行があった場合 当社からの連絡に対し，一定期間返答がない場合 本サービスについて，最終の利用から一定期間利用がない場合 その他，当社が本サービスの利用を適当でないと判断した場合 前項各号のいずれかに該当した場合，ユーザーは，当然に当社に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。 当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</p>
  <h2>第9条（退会）</h2>
    <p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>
  <h2>第10条（保証の否認および免責事項）</h2>
    <p>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。 当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。 前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。 当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</p>
  <h2>第11条（サービス内容の変更等）</h2>
    <p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>
  <h2>第12条（利用規約の変更）</h2>
    <p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。</p>
  <h2>第13条（個人情報の取扱い）</h2>
    <p>当社は，本サービスの利用によって取得する個人情報については，当社「<%= link_to "プライバシーポリシー", pages_policy_path %>」に従い適切に取り扱うものとします。</p>
  <h2>第14条（通知または連絡）</h2>
    <p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>
  <h2>第15条（権利義務の譲渡の禁止）</h2>
    <p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
  <h2>第16条（準拠法・裁判管轄）</h2>
    <p>本規約の解釈にあたっては，ジンバブエ法を準拠法とします。 本サービスに関して紛争が生じた場合には，ジンバブエ最高裁判所を専属的合意管轄とします。以上</p>
</div>

src/app/views/pages/top.html.erb
<% provide(:title) %>
<%= render 'partial/map' %>
<div class="row">
  <div class="top col-xl-10 mt-5 mx-auto">
    <h2>『ストバスぽっと』</h2>
    <p>マップにある緑色のマーカーは、バスケットボールのゴールがあるスポットです！</p>
    <p>詳細を確認するには、ログインが必要です。</p>
    <p>さあ、今すぐ「ストバスぽっと」に登録し、投稿を確認しましょう！</p>
    <div class="mt-3">
      <%= link_to "今すぐ登録する！", new_user_registration_path, class: "top-button btn-primary" %>
    </div>
  </div>
</div>

src/app/views/partial/_footer.html.erb
<div class="row">
  <div class="col-10 mx-auto">
    <footer class="footer mx-auto">  
        <nav class="wrapper">
          <ul class="wrapper-item">
            <li><%= link_to "「ストバスぽっと」とは？", pages_about_path, class: "item" %></li>
            <li><%= link_to "利用規約", pages_terms_path, class: "item" %></li>
            <li><%= link_to "プライバシーポリシー", pages_policy_path, class: "item" %></li>
          </ul>
        </nav>
    </footer>

    <footer>
      <div class="navbar navbar-expand-lg navbar-light justify-content-center col-10 mx-auto" style="background-color: #ffbf1f;">
        <p><small>&copy; 2021 ストバスぽっと</small></p>
      </div>
    </footer>
  </div>
</div>

src/app/views/partial/_modal.html.erb
<button type="button" class="sidebtn btn-link pull-right" data-bs-toggle="modal" data-bs-target="#exampleModal">
  投稿方法についてはこちら
</button>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <h5 class="modal-title" id="exampleModalLabel">投稿方法について</h5>
        <h6>レビュー場所を地名から検索する際には、「レビュー場所」に地名、公園名等を記入し検索ボタンをクリックしてください。 地名から住所が検索され、自動的に住所欄に住所が入力されますので、テキストを入力し投稿してください。</h6>
        <h6>また、地図をクリックすればクリックしたポイントにピンが立ち、住所が表示されます。 必要に応じて住所を変更した後、テキストを入力し投稿してください。</h6>
      </div>
    </div>
  </div>
</div>

src/app/views/partial/_navbar.html.erb
<div class="row">
  <div class="col-10 mx-auto">
    <nav class="navbar navbar-expand-lg navbar-light mx-auto" style="background-color: #ffbf1f;">
      <% if user_signed_in? %>
        <%= link_to "ストバスぽっと", posts_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "ストバスぽっと", root_path, class: "navbar-brand" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" style="background-color: #ffbf1f;">
          <li><%= link_to "「ストバスぽっと」とは？", pages_about_path, class: "nav-item" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Home", posts_path, class: "nav-item" %></li>
            <li><%= link_to "設定", edit_user_registration_path, class: "nav-item" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-item" %></li>
            <li><%= link_to "マイページ", user_path(current_user), class: "nav-item" %></li>
          <% else %>
            <li><%= link_to "Home", root_path, class: "nav-item" %></li>
            <li><%= link_to "ログイン", user_session_path, class: "nav-item" %></li>
            <li><%= link_to "新規登録", new_user_registration_path, class: "nav-item" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</div>